# Generated by Django 4.1.7 on 2023-02-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
