# Generated by Django 4.1.7 on 2023-02-24 22:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
