# Generated by Django 4.1.7 on 2023-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.CharField(max_length=255),
        ),
    ]
